---
is_new_cluster: false
env_nameserver: 192.168.2.1
elasticsearch_cluster_name: updox
elasticsearch_http_port: 9200
elasticsearch_transport_port: 9300
kibana_port: 5601
nginx_http_port: 80
nginx_https_port: 443
Xms_memory_amount: 256m
Xmx_memory_amount: 256m
cluster_join_async_seconds: 600
cluster_join_poll_seconds: 10
master_node: "{{groups['elasticsearch'][0]}}"
elasticsearch_certutil: /usr/share/elasticsearch/bin/elasticsearch-certutil
es_certs_dir: /etc/elasticsearch/certs