---
# tasks file for kibana_setup

- name: Install kibana 
  package:
    name: kibana
    state: present
    update_cache: true
  register: kabana_install
  tags: install_kibana

- name: change server.host in the kibana.yml file 
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: '#server.host: ""'
    line: 'server.host: "{{hostvars[ansible_hostname].ansible_facts.eth0.ipv4.address}}"'
    state: present
  tags: install_kibana

- name: change server.publicBaseUrl in the kibana.yml file 
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: '#server.publicBaseUrl: ""'
    line: 'server.publicBaseUrl: "http://{{ansible_hostname}}:{{kibana_port}}"'
    state: present
  tags: install_kibana

# A token is only good for 30 minutes, so we create it here to make sure we have a good token.

- name: Get elasticsearch enrollment token
  shell: "/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana"
  register: kibana_token
  delegate_to: "{{master_node}}"
  when: new_kibana_node == true and ansible_hostname == groups['kibana'][0]
  tags: install_kibana, enroll_kibana

- name: save token for kibana
  copy:
    dest: files/{{elasticsearch_cluster_name}}_kibana_token
    content: "{{ kibana_token.stdout }}"
    mode: 0440
    owner: root
    group: root
  delegate_to: localhost
  when: new_kibana_node == true and ansible_hostname == groups['kibana'][0]
  tags: install_kibana, enroll_kibana
  
- name: enroll in elasticsearch cluster
  shell: "/usr/share/kibana/bin/kibana-setup --enrollment-token {{ lookup('file','files/{{elasticsearch_cluster_name}}_kibana_token') }} || echo'' "
  register: enrollment_result
  when: new_kibana_node == true 
  ignore_errors: true
  tags: install_kibana, enroll_kibana

- name: enable kibana  
  shell: systemctl enable kibana
  tags: install_kibana

- name: restart_kibana
  service:
    name: kibana
    state: restarted
    enabled: yes
  tags: kibana_setup, restart_kibana, enroll_kibana

- name: enrollment result
  debug:
    msg: "{{enrollment_result.stdout}}"
  when: new_kibana_node == true
  tags: install_kibana, enroll_kibana