#!/bin/bash

# This script does NOT create the LOGDIR!
# It only creates simulated log files in the LOGDIR

LOGDIR="logs"

for m in `seq -w 01 04`; do
  for d in `seq -w 1 28`; do
    for l in `seq -w 1 20`; do touch ${LOGDIR}/name-$l-2022.${m}.$d; done
  done
done

