---
# Play to install ELK stack
#
# !!! BE SURE TO SET is_new_cluster TO THE CORRECT VALUE BEFORE RUNNING !!!
# !!! it is in the group_vars/all.yml file
#

# To rerun deps for this group, for instance, to apply new FW rules
# ansible-playbook env_install_update.yml --limit elasticsearch -e force_reinstall=true -e is_new_cluster=false -t env_deps 
# or other tags

- hosts: "{{ elasticsearch_cluster_name | default('all') }}"   # <-- name of the elasticsearch cluster, applies env deps
  become: true
  vars:
  roles: 
    - install_env_deps

- hosts: elasticsearch   # <-- name of ansible hosts group containing the elasticsearch servers
  become: true
  vars:
    is_new_cluster: true # <-- ALERT!!! Set this to false if you are not building a new cluster!!! 
    force_reinstall: false
  roles: 
    - elasticsearch_setup
  
- hosts: kibana   # <-- name of ansible hosts group containing the kibana servers
  become: true
  vars:
    new_kibana_node: true # <-- ALERT!!! Set this if you are not setting up a new node!!!
  roles:
    - kibana_setup
  
- hosts: nginx   # <-- name of ansible hosts group containing the nginx servers
  become: true
  roles: 
    - nginx_setup 
  