---
# tasks file for install_env_deps

# Needed for name resolution in my lab - quick fix
- name: Rewrite /etc/hosts
  lineinfile: 
    dest: /etc/hosts
    regexp: '127.0.1.1'
    line: "{{hostvars[ansible_hostname].ansible_facts.eth0.ipv4.address}} {{ansible_hostname}}"
    state: present
  tags: env_deps
  
# Needed for name resolution in my lab - quick fix
- name: Rewrite /etc/resolv.conf
  lineinfile: 
    dest: /etc/resolv.conf
    regexp: 'nameserver'
    line: "nameserver {{env_nameserver}}"
    state: present
  tags: env_deps

- name: Add apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  tags: env_deps

- name: Add apt repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present
    update_cache: true
  tags: env_deps

- name: Install deps
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ install_deps }}"
  tags: env_deps

- name: create iptables dirs
  file:
    path: /etc/iptables
    state: directory
  tags: env_deps, fw_rules
  
- name: template iptables v4
  template:
    src: templates/iptables-rules.v4.j2
    dest: /etc/iptables/rules.v4
    mode: 0644 # <-- according to the install! 
    owner: root
    group: root
  tags: env_deps, fw_rules 
  
- name: reload iptables
  community.general.iptables_state:
    state: restored
    path: /etc/iptables/rules.v4
  async: 10
  poll: 0
  tags: env_deps, fw_rules