---
# tasks file for nginx_setup

- name: Install env deps
  include_tasks: 
    file: tasks/env_wide_deps.yml  
  tags: env_deps

- name: Install nginx 
  apt:
    name:
      - nginx
    state: present
    update_cache: true
    cache_valid_time: 21600


